[package]
name = "tantivy-analysis-contrib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.16"
rust_icu_utrans = "2.0"
rust_icu_sys = "2.0"