[package]
name = "tantivy-analysis-contrib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.16"
rust_icu = "2.0"
unicode-segmentation = "1.9"