name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version released (only version number)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - uses: taiki-e/install-action@cargo-hack
      - name: Test features
        run: cargo hack check --all --each-feature --clean-per-run --no-dev-deps
      - name: Install
        run: cargo install cargo-edit
      - name: Set version
        run: cargo set-version ${{ github.event.inputs.release_version }}
      - name: Commit new version
        run: |
          git config user.name "$env.GITHUB_ACTOR"
          git config user.email "$env.GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Prepare v${{ github.event.inputs.release_version }}"
          git push
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.event.inputs.release_version }}
      - name: Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
      - name: Incremente version
        run: |
          cargo set-version --bump patch
          git add .
          git commit -m "Prepare next version"
          git push

