name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - uses: taiki-e/install-action@cargo-hack
      - name: Test features
        run: cargo hack check --all --each-feature --clean-per-run --no-dev-deps
      - name: Install
        run: cargo install cargo-edit
      - name: Bump new version
        run: cargo set-version --bump ${{ github.event.inputs.release_type }}
      - name: Save version to be reuse in subsequent runs
        run: |
          export VERSION=`cargo tree --depth 0 | grep tantivy-analysis-contrib | awk '{print $2}'`
          echo "VERSION=$VERSION"  >> $GITHUB_ENV
      - name: Commit new version
        run: |
          git config user.name "$env.GITHUB_ACTOR"
          git config user.email "$env.GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Prepare ${{ env.VERSION }}"
          git push
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION }}
      - name: Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

